server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  application:
    name: medical-clinic-app
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 200
        one-indexed-parameters: true
  profiles:
    active: [test]
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
springdoc:
  swagger-ui:
    operations-sorter: method
