spring:
  datasource:
    url: jdbc:h2:mem:test_clinic
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  sql:
    init:
      platform: h2
logging:
  level:
    org:
      hibernate:
        sql: info
